# anibase/integrations/__init__.py
"""Subpaket integrasi eksternal (AniList, Tenrai, Jikan, AniSkip, MyAnimeList, Discord)."""

from anibase.integrations.aniskip import (
    get_aniskip_times,
)
from anibase.integrations.mal import (
    load_mal_auth,
    save_mal_auth,
    clear_mal_auth,
    is_mal_authenticated,
    load_mal_scrobble_history,
    record_mal_scrobble,
    clear_mal_scrobble_record,
    cleanup_mal_oauth_sessions,
    get_valid_mal_token,
    fetch_mal_user_profile,
    load_mal_profile_cache,
    save_mal_profile_cache,
    clear_mal_profile_cache,
    get_mal_user_full_profile,
    get_mal_animelist_cache_path,
    load_mal_animelist_cache,
    save_mal_animelist_cache,
    get_mal_user_animelist,
    enrich_mal_list_with_local_library,
    update_mal_user_anime_status,
    scrobble_episode_to_mal,
    trigger_mal_scrobble_if_enabled,
)
from anibase.integrations.discord import (
    reset_discord_rpc,
    get_discord_rpc_client,
    update_discord_rpc,
    clear_discord_rpc,
    run_discord_rpc_worker,
    reconcile_discord_presence,
    discord_media_metadata,
    discord_media_description,
    discord_media_artwork,
    start_external_discord_presence,
    monitor_discord_presence,
    start_discord_presence_monitor,
    accept_discord_presence_event,
    dispatch_discord_rpc_task,
    dispatch_discord_rpc_update,
    dispatch_discord_rpc_clear,
    clear_discord_rpc_when_process_exits,
)
from anibase.integrations.jikan import (
    build_seiyuu_role_from_jikan,
    fetch_jikan_seiyuu_detail,
)
from anibase.integrations.tenrai import (
    unwrap_tenrai_data,
    tenrai_image_url,
    parse_tenrai_duration,
    normalize_tenrai_status,
    normalize_tenrai_format,
    tenrai_named_values,
    adapt_tenrai_characters,
    adapt_tenrai_relations,
    adapt_tenrai_recommendations,
    get_next_tenrai_broadcast_at,
    adapt_tenrai_anime_metadata,
    tenrai_wait_for_rate_limit,
    fetch_tenrai_json,
    get_tenrai_anime_info,
    search_tenrai_anime,
    adapt_tenrai_schedule,
    get_tenrai_airing_schedule,
    adapt_tenrai_studio_projects,
    get_tenrai_studio_projects,
    cache_tenrai_seiyuu_payload,
    build_seiyuu_role_from_tenrai,
    normalize_tenrai_role_images,
    fetch_tenrai_seiyuu_detail,
    get_cached_tenrai_seiyuu_detail,
)
from anibase.integrations.anilist import (
    EXTERNAL_ANIME_QUERY,
    mark_anilist_unavailable,
    can_attempt_anilist,
    mark_anilist_available,
    refresh_anilist_metadata,
    start_anilist_recovery,
    get_anilist_info,
    search_anilist_anime,
    fetch_anilist_studio_projects,
    build_seiyuu_role_from_anilist,
    fetch_anilist_seiyuu_detail,
)
